[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.setuptools', 'python311Packages.wheel']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install discord.py==2.5.2',
  'pip install flask==3.1.1', 
  'pip install psycopg2-binary==2.9.9',
  'pip install requests==2.31.0',
  'pip install aiohttp==3.12.13'
]

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'python main.py'